import { fontFamily } from './constants';

export const theme = {
  palette: {
    black: '#000000',
    gray: 'rgba(0, 0, 0, 0.7)',
    secondaryGray: 'rgba(0, 0, 0, 0.3)',
    tetriaryGray: 'rgba(0, 0, 0, 0.1)',
    quaternaryGray: 'rgba(0, 0, 0, 0.03)',
    white: '#FFFFFF',
    lightGreen: '#E3FD9C',
    green: '#91C600',
    red: '#EE5151',
    orange: '#FDCA69',
    blue: '#0E46CA',
    skyBlue: '#82ABFF',
    arctic: '#BDE3FF',
    lightBlue: '#E7F5FF',
    blueWhite: '#F4FAFE',
    overlay: '#FBFBFB',
    outline: '#E2E2E2',
    lightGray: '#F6F6F6',
    secondary: '#4D4D4D',
  },
  typography: {
    fontFamily,
    color: '#000000',
    h1: {
      fontSize: '26px',
      lineHeight: '28px',
      fontStyle: 'normal',
      fontWeight: '700',
      color: '#020202',
      font: `normal 700 26px/28px ${fontFamily}`,
    },
    h2: {
      fontSize: '20px',
      lineHeight: '24px',
      fontStyle: 'normal',
      fontWeight: '700',
      font: `normal 700 20px/24px ${fontFamily}`,
    },
    h3: {
      fontSize: '18px',
      lineHeight: '22px',
      fontWeight: '600',
      fontStyle: 'normal',
      font: `normal 600 18px/22px ${fontFamily}`,
    },
    subtitle1: {
      fontSize: '16px',
      lineHeight: '24px',
      fontWeight: '600',
      fontStyle: 'normal',
      font: `normal 600 16px/24px ${fontFamily}`,
    },
    subtitle2: {
      fontSize: '14px',
      lineHeight: '20px',
      fontWeight: '600',
      fontStyle: 'normal',
      font: `normal 600 14px/20px ${fontFamily}`,
    },
    body1: {
      fontSize: '16px',
      lineHeight: '24px',
      fontWeight: '400',
      fontStyle: 'normal',
      font: `normal 400 16px/24px ${fontFamily}`,
    },
    body2: {
      fontSize: '14px',
      lineHeight: '20px',
      fontWeight: '400',
      fontStyle: 'normal',
      font: `normal 400 14px/20px ${fontFamily}`,
    },
    body3: {
      fontSize: '16px',
      lineHeight: '24px',
      fontWeight: '400',
      fontStyle: 'normal',
      font: `normal 400 16px/24px ${fontFamily}`,
    },
    button: {
      fontSize: '16px',
      lineHeight: '20px',
      fontWeight: '600',
      fontStyle: 'normal',
      font: `normal 600 16px/20px ${fontFamily}`,
    },
    caption: {
      fontSize: '12px',
      lineHeight: '16px',
      fontWeight: '400',
      fontStyle: 'italic',
      font: `italic 400 12px/16px ${fontFamily}`,
    },
    overline: {
      fontSize: '12px',
      lineHeight: '16px',
      fontWeight: '600',
      fontStyle: 'normal',
      font: `normal 600 12px/16px ${fontFamily}`,
    },
    logo: {
      color: '#072365',
      fontWeight: '900',
      fontSize: '18.85px',
      lineHeight: '17.39px',
      fontStyle: 'italic',
    },
    megaFont: {
      fontStyle: 'normal',
      fontWeight: '700',
      fontSize: '70px',
      lineHeight: '120%',
      font: `normal 700 70px/120% ${fontFamily}`,
    },
  },
  breakpoints: {
    smallMobile: '360px',
    mobile: '600px',
    smallMobileTablet: '855px',
    mobiletablet: '905px',
    mediumDesktop: '1240px',
    largeDesktop: '1440px',
  },
};
